"""rename department

Revision ID: 27cf29710bbb
Revises: 8bfb26b964d7
Create Date: 2025-08-28 20:38:06.181636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27cf29710bbb'
down_revision = '8bfb26b964d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
