"""rename address to location

Revision ID: 685561488a8d
Revises: 27cf29710bbb
Create Date: 2025-08-28 21:18:55.448708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685561488a8d'
down_revision = '27cf29710bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###